name: Notify

inputs:
  telegram_message:
    required: false
    default: |
      ${{ github.event_name }}
      ${{ github.repository_owner }}
      ${{ github.repository }}
      Commit message: ${{ github.event.commits[0].message }}
      https://github.com/${{ github.repository }}/commit/${{ github.sha }}
  telegram_photo:
    required: false
  telegram_document:
    required: false

  ## secrets
  TELEGRAM_TOKEN:
    required: true
  TELEGRAM_TO:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setting timezone and installing jcal
      uses: davoudarsalani/action-jcal@master

    - name: Getting date/time
      shell: bash
      run: |
        date_time="$(jdate '+%Y-%m-%d %H:%M:%S %A')" || date_time="$(date '+%Y-%m-%d %H:%M:%S %A')"
        echo "date_time=$date_time" >> $GITHUB_ENV

    - name: Sending telegram message
      uses: davoudarsalani/action--telegram@master
      with:
        token: ${{ inputs.TELEGRAM_TOKEN }}
        to: ${{ inputs.TELEGRAM_TO }}
        message: |
          ${{ env.date_time }}

          ${{ inputs.telegram_message }}
        photo:
          ${{ inputs.telegram_photo }}
        document:
          ${{ inputs.telegram_document }}
