name: Notify

inputs:
  telegram_message:
    required: false
    default: |
      ${{ github.event_name }}
      ${{ github.repository_owner }}
      ${{ github.repository }}
      Commit message: ${{ github.event.commits[0].message }}
      https://github.com/${{ github.repository }}/commit/${{ github.sha }}
  telegram_photo:
    required: false
  telegram_document:
    required: false

  ## secrets
  TELEGRAM_TOKEN:
    required: true
  TELEGRAM_TO:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setting jdate_source
      shell: bash
      run: echo "jdate_source=docker-jdate" >> $GITHUB_ENV

    - name: Pulling/cloning/downloading jdate
      uses: davoudarsalani/action-jdate@master
      with:
        source: '${{ env.jdate_source }}'

    - name: Getting date/time
      shell: bash
      run: |
        case '${{ env.jdate_source }}' in
          docker-jdatetime ) date_time="$(docker run --rm -t davoudarsalani/jdatetime python -c "import jdatetime; print(jdatetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S %A'))")" ;;
          docker-jdate ) date_time="$(docker run --rm -t davoudarsalani/jdate jdate '+%Y-%m-%d %H:%M:%S %A')" ;;
          * ) date_time="$(jdate '+%Y-%m-%d %H:%M:%S %A')" ;;
        esac
        echo "date_time=$date_time" >> $GITHUB_ENV

    - name: Sending telegram message
      shell: bash
      run: |
        wget -q 'https://raw.githubusercontent.com/davoudarsalani/scripts/master/telegram'
        chmod +x ./telegram
        ./telegram \
          -t '${{ inputs.TELEGRAM_TOKEN }}' \
          -c '${{ inputs.TELEGRAM_TO }}' \
          -M \
          -T '${{ env.date_time }}' \
          -f '${{ inputs.telegram_document }}' \
          -i '${{ inputs.telegram_photo }}' \
          '${{ inputs.telegram_message }}'
