name: Notify

inputs:
  telegram_message:
    required: false
    default: |
      ${{ github.event_name }}
      ${{ github.repository_owner }}
      ${{ github.repository }}
      Commit mmmmessage: ${{ github.event.commits[0].message }}
      https://github.com/${{ github.repository }}/commit/${{ github.sha }}
  telegram_photo:
    required: false

  ## secrets
  TELEGRAM_TOKEN:
    required: false
  TELEGRAM_TO:
    required: false

runs:
  using: "composite"
  steps:
    - name: Setting timezone and installing jcal
      shell: bash
      run: |
        wget -q https://raw.githubusercontent.com/${{ github.repository_owner }}/scripts/master/gb
        source gb
        set_timezone
        install_jcal

        date_time="$(jdate '+%Y-%m-%d %H:%M:%S %A')" || date_time="$(date '+%Y-%m-%d %H:%M:%S %A')"
        echo "date_time=$date_time" >> $GITHUB_ENV

    - name: Sending telegram message
      uses: davoudarsalani/action--telegram@master
      with:
        token: ${{ inputs.TELEGRAM_TOKEN }}
        to: ${{ inputs.TELEGRAM_TO }}
        message: |
          ${{ env.date_time }}

          ${{ inputs.telegram_message }}
        photo:
          ${{ inputs.telegram_photo  }}
