name: Notify

inputs:
  telegram_message:
    required: false
    default: |
      ${{ github.event_name }}
      ${{ github.repository_owner }}
      ${{ github.repository }}
      Commit message: ${{ github.event.commits[0].message }}
      [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
  telegram_photo:
    required: false
  telegram_document:
    required: false

  ## I couldn't set jdate_source as env variable so let's set it as input for the moment
  jdate_source:
    required: false
    default: 'docker'

  ## secrets
  TELEGRAM_TOKEN:
    required: true
  TELEGRAM_TO:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Installing jdate
      uses: davoudarsalani/action-jdate@master
      with:
        source: '${{ inputs.jdate_source }}'

    - name: Getting date/time
      shell: bash
      run: |
        case '${{ inputs.jdate_source }}' in
          docker )    date_time="$(docker run --rm -t davoudarsalani/jdate jdate '+%Y-%m-%d %H:%M:%S %A')" ;;
          jdatetime ) date_time="$(python -c "import jdatetime; print(jdatetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S %A'))")" ;;
          * )         date_time="$(jdate '+%Y-%m-%d %H:%M:%S %A')" ;;
        esac
        echo "date_time=$date_time" >> $GITHUB_ENV

    - name: Sending telegram message
      shell: bash
      run: |
        wget -q 'https://raw.githubusercontent.com/davoudarsalani/scripts/master/telegram'
        chmod +x ./telegram
        ./telegram \
          -t '${{ inputs.TELEGRAM_TOKEN }}' \
          -c '${{ inputs.TELEGRAM_TO }}' \
          -T '${{ env.date_time }}' \
          '${{ inputs.telegram_message }}'
          # -f '${{ inputs.telegram_document }}' \
          # -i '${{ inputs.telegram_photo }}' \
