name: Notify

inputs:
  telegram_message:
    required: false
    default: |
      ${{ github.event_name }}
      ${{ github.repository_owner }}
      ${{ github.repository }}
      Commit message: ${{ github.event.commits[0].message }}
      https://github.com/${{ github.repository }}/commit/${{ github.sha }}
  telegram_photo:
    required: false
  telegram_document:
    required: false

  ## secrets
  TELEGRAM_TOKEN:
    required: true
  TELEGRAM_TO:
    required: true

env:
  jcal_source: 'jdatetime'

runs:
  using: 'composite'
  steps:
    - name: Setting timezone and installing jcal
      uses: davoudarsalani/action-jcal@master
      with:
        source: 'jdatetime'

    - name: Getting date/time
      shell: bash
      run: |
        case ${{ env.jcal_source }} in
          docker )
            date_time="$(docker run --rm davoudarsalani/jcal \
              python3 -c "import jdatetime; print(jdatetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S %A'))")"
          jdatetime )
            date_time="$(python -c "import jdatetime; print(jdatetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S %A %A'))")"
          ;;
          * )
            date_time="$(jdate '+%Y-%m-%d %H:%M:%S %A')"
          ;;
        esac
        echo "date_time=$date_time" >> $GITHUB_ENV

    - name: Sending telegram message
      uses: davoudarsalani/action--telegram@master
      with:
        token: ${{ inputs.TELEGRAM_TOKEN }}
        to: ${{ inputs.TELEGRAM_TO }}
        message: |
          ${{ env.date_time }}

          ${{ inputs.telegram_message }}
        photo:
          ${{ inputs.telegram_photo }}
        document:
          ${{ inputs.telegram_document }}
